version: "3.8"

services:
  postgres-api-payments:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - hexafood-bridge
  api-payments:
    container_name: hexafood-api-payments
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
        - postgres-api-payments
        - localstack
    networks:
    - hexafood-bridge
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=1
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./docker:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh"
    networks:
      - hexafood-bridge

networks:
  hexafood-bridge:
    driver: bridge