version: '3.1'

services:
  postgres-api-payments:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - hexafood-bridge
  api-payments:
    container_name: hexafood-api-payments
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
        - postgres-api-payments
    networks:
      - hexafood-bridge
networks:
  hexafood-bridge:
    driver: bridge