version: '3.1'

services:

  db:
    hostname: db
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - techchallenge

  server:
    hostname: server
    image: cezaodabahia/1soattechchallenge:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - techchallenge
    depends_on:
      - db

networks:
  techchallenge:
    driver: bridge